/* CampusLink Service Worker — Push Notifications + Workbox Caching */

import { precacheAndRoute } from 'workbox-precaching';

// Inject the manifest generated by vite-plugin-pwa
precacheAndRoute(self.__WB_MANIFEST);

// Handle messages from the client (e.g., skip waiting to update the SW)
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Handle incoming Web Push notifications
self.addEventListener('push', (event) => {
  let payload = {};
  if (event.data) {
    try {
      payload = event.data.json();
    } catch (e) {
      payload = { title: 'CampusLink Alert', body: event.data.text() };
    }
  }

  const title = payload.title || '[ CAMPUSLINK EVENT ALERT ]';
  const options = {
    body: payload.body || 'A new event has been published on campus!',
    icon: payload.icon || '/favicon.ico',
    badge: payload.badge || '/favicon.ico',
    tag: payload.tag || 'campuslink-event',
    data: {
      url: payload.url || '/',
      eventId: payload.eventId || null,
    },
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

// Handle notification click to open or focus the app
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const targetUrl = event.notification.data?.url || '/';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      for (const client of windowClients) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          if ('navigate' in client) {
            client.navigate(targetUrl);
          }
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }
    })
  );
});
